# Generated by Django 6.0.3 on 2026-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
