# Generated by Django 6.0.3 on 2026-04-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_favorite_lat_favorite_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_daily_quota',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_used_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ai_quota_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_quota',
            field=models.IntegerField(default=30),
        ),
    ]
