# Generated by Django 6.0.3 on 2026-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_ai_daily_quota_user_ai_used_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ai_used_today',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_ai_quota_reset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_quota_reset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='used_today',
        ),
        migrations.AlterField(
            model_name='user',
            name='ai_daily_quota',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_quota',
            field=models.IntegerField(default=15),
        ),
    ]
