# Generated by Django 6.0.3 on 2026-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_ai_used_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
