# Generated by Django 6.0.3 on 2026-04-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_popularsearch_usersearchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerAiSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(default='v1', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('mixed', 'Mixed'), ('negative', 'Negative')], max_length=20)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('export_friendly', models.BooleanField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source_review_count', models.PositiveIntegerField(default=0)),
                ('source_fingerprint', models.CharField(blank=True, max_length=64)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='dealers.dealer')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
