# Generated by Django 6.0.3 on 2026-04-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_dealeraisummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealeraisummary',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealeraisummary',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
