# Generated by Django 6.0.3 on 2026-04-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0004_dealeraisummary_last_retry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealeraisummary',
            name='reviews_total_count_at_sync',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
