# Generated by Django 6.0.3 on 2026-04-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_dealeraisummary_reviews_total_count_at_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealeraisummary',
            name='is_limited_sample',
            field=models.BooleanField(default=False),
        ),
    ]
