# Generated by Django 6.0.3 on 2026-04-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_dealeraisummary_is_limited_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
